FROM ubuntu:xenial

RUN apt-get update && \
    apt-get install -y --no-install-recommends software-properties-common && \
    # MediaElch requires a more modern GCC:
    add-apt-repository ppa:ubuntu-toolchain-r/test

RUN apt-get update && \
    apt-get -y --no-install-recommends install \
        g++-8 gcc-8 \
        build-essential \
        git \
        cmake \
        wget \
        ffmpeg \
        libmediainfo-dev \
        libcurl4-gnutls-dev \
        qt5-default \
        qtmultimedia5-dev \
        qtdeclarative5-dev \
        qtdeclarative5-models-plugin \
        libqt5opengl5 \
        libqt5opengl5-dev
